-- Skrypt do stworzenia tabeli w Supabase SQL Editor
-- Wklej to w Supabase -> SQL Editor -> New Query -> Run

create table if not exists public.debts (
    id bigint generated by default as identity primary key,
    name text not null,
    category text default 'Prywatne',
    initial_amount numeric not null,
    current_amount numeric not null,
    rate text default '?',
    installment numeric,
    priority integer default 0,
    note text,
    created_at timestamptz default now()
);

-- Włącz RLS (Row Level Security) - dla uproszczenia na start pozwalamy na wszystko
-- W wersji produkcyjnej warto to ograniczyć do zalogowanych użytkowników
alter table public.debts enable row level security;

create policy "Allow public access" 
on public.debts for all 
using (true) 
with check (true);
