-- Skrypt do stworzenia tabel w Supabase SQL Editor
-- Wklej to w Supabase -> SQL Editor -> New Query -> Run

create table if not exists public.debts (
    id bigint generated by default as identity primary key,
    name text not null,
    category text default 'Prywatne',
    initial_amount numeric not null,
    current_amount numeric not null,
    rate text default '?',
    installment numeric,
    priority integer default 0,
    note text,
    created_at timestamptz default now()
);

-- Tabela płatności (historia)
create table if not exists public.payments (
    id bigint generated by default as identity primary key,
    debt_id bigint references public.debts(id) on delete cascade,
    amount numeric not null,
    created_at timestamptz default now()
);

-- Włącz RLS (Row Level Security)
alter table public.debts enable row level security;
alter table public.payments enable row level security;

-- Polisy (publiczny dostęp dla uproszczenia)
create policy "Allow public access for debts" 
on public.debts for all using (true) with check (true);

create policy "Allow public access for payments" 
on public.payments for all using (true) with check (true);
